project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()

project/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

project/core/models.py
from django.db import models

# Create your models here.

project/servicios/models.py
from django.db import models

# Create your models here.

project/users/models.py
from django.db import models

# Create your models here.
# users/models.py

class Perfil_de_Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)  # Campo para almacenar números de teléfono
    fecha_nacimiento = models.DateField()
    

class Direccion(models.Model):
    usuario = models.ForeignKey(Perfil_de_Usuario, on_delete=models.CASCADE)
    calle = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=50)
    codigo_postal = models.CharField(max_length=10)

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/core/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .forms import CustomAuthenticationForm, CustomUserCreationForm


# @login_required
def home(request):
        return render(request, "core/index.html")


class CustomLoginView(LoginView):
        authentication_form = CustomAuthenticationForm
        template_name = "core/login.html"


@staff_member_required
def register(request: HttpRequest) -> HttpResponse:
        if request.method == "POST":
                form = CustomUserCreationForm(request.POST)
        if form.is_valid():
                form.save()
                return render(request, "core/index.html", {"mensaje": "Usuario creado"})
        else:
                form = CustomUserCreationForm()
        return render(request, "core/register.html", {"form": form})

project/servicios/views.py
from django.shortcuts import render

# Create your views here.

project/users/views.py
from django.shortcuts import render

# Create your views here.

from . import models

def home(request):
    return render(request, 'users/home.html')

def about(request):
    return render(request, 'users/about.html')

def contact(request):
    return render(request, 'users/contact.html')

def projects(request):
    return render(request, 'users/projects.html')

project/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>
        {% block title %}
        App Coderhouse
        {% endblock title %}
    </title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Responsive navbar-->
    {% include 'core/components/navbar.html' %}
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">
        <div class="row align-items-center my-5">
            <h1 class="pb-lg-3 text-white bg-info px-3 py-2 rounded">
                {% block titulo %}
                App Coder
                {% endblock titulo %}
            </h1>
        </div>
        {% block contenido %}
        {% endblock contenido %}
    </div>
    <!-- Footer -->
    {% include 'core/components/footer.html' %}
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'core/js/scripts.js' %}"></script>
</body>

</html>

project/core/templates/core/components/footer.html
<footer class="py-2 bg-dark fixed-bottom">
    <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">Mi sitio hecho en Coderhouse 2024</p>
    </div>
</footer>

project/core/templates/core/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">La Caja de Pandora</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link {% if request.path == " /" %} active {% endif %}"
                        aria-current="page" href="{% url 'core:home' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == " /about" %} active {% endif %}"
                        href="#!">Nosotros</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link {% if request.path == " /cliente/" %} active {% endif %}"
                        href="{% url 'cliente:home' %}">Clientes</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == " /producto/" %} active {% endif %}"
                        href="{% url 'producto:home' %}">Producto</a></li>
                <li class="nav-item"><a class="nav-link text-bg-info">{{ user.username }}</a></li>
                <li class="nav-item">
                    <form action="{% url 'core:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-dark {{ fontsize }} ">Logout</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link {% if request.path == " /login/" %} active {% endif %}"
                        href="{% url 'core:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == " /register/" %} active {% endif %}"
                        href="{% url 'core:register' %}">Registrarse</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
{% include 'core/components/titulo1.html' with titulo="App Coder" %}
{% endblock titulo %}
{% block contenido %}

{% if user.is_authenticated %}
{{ mensaje }}
<p class="fs-2">Bienvenido {{ user.username }}</p>
{% endif %}
<!-- Heading Row-->
<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="col-lg-7">
        <img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'core/img/caja.webp' %}" alt="..." />
    </div>
    <div class="col-lg-5">
        <h1 class="font-weight-light">La Caja de la Pandora</h1>
        <p>
            La Caja de Pandora: Desbloquea tu creatividad con nuestra plataforma web. Encuentra inspiración, comparte
            ideas y colabora en proyectos. ¡Libera todo tu potencial creativo en un solo lugar!
        </p>
        <a class="btn btn-primary" href="https://wa.me/542619999999" target="_blank">WhatsApp</a>
    </div>
</div>
<!-- Call to Action-->
<div class="card text-white bg-secondary my-5 py-4 text-center">
    <div class="card-body">
        <p class="text-white m-0">
            This call to action card is a great place to showcase some important information or display a clever
            tagline!
        </p>
    </div>
</div>
<!-- Content Row-->
<div class="row gx-4 gx-lg-5">
    {% include 'core/components/card.html' with titulo="Tarjeta 1" texto="Promociones" %}
    {% include 'core/components/card.html' with titulo="Tarjeta 2" texto="Lorem ipsum dolor sit amet consectetur
    adipisicing elit. In perferendis repellat quo earum ut, ducimus repudiandae maxime eaque sint, omnis placeat ex
    necessitatibus rerum dicta itaque dolorem consequatur deleniti praesentium?" %}
    {% include 'core/components/card.html' with titulo="Tarjeta 3" %}
    {% include 'core/components/card.html' with texto="Promociones" %}
</div>
{% endblock contenido %}

project/core/templates/core/login.html
{ % extends 'core/base.html' % } 

{% block title %}
    Login
{% endblock title %}

{% block content %}

    <div class="container">
        <h1 class="mt-4">LogIn</h1>
    </div>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{ % url 'core:index' % }">

        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{% url 'producto:productocategoria_list' %}" class="btn btn-secondary"></a>
    </form>

{% endblock content %}

project/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block title %}
    Register
{% endblock title %}

{% block content %}

    <div class="container">
        <h1 class="mt-4">Registro de usuario</h1>
    </div>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Registrar nuevo usuario</button>
    </form>

{% endblock content %}